# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020 Intel Corporation
# Copyright(c) 2018-2019 The University of New Hampshire
#

from enum import Enum


class FlowRuleType(Enum):
    INGRESS = "ingress"
    EGRESS = "egress"
    BOTH = ""


class FlowItemType(Enum):
    UDP = "udp"
    TCP = "tcp"
    SCTP = "sctp"
    IPV4 = "ipv4"
    IPV6 = "ipv6"
    END = "end"
    VOID = "void"
    INVERT = "invert"
    ANY = "any"
    RAW = "raw"
    ETH = "eth"
    VLAN = "vlan"
    VXLAN = "vxlan"
    GRE = "gre"
    VXLAN_GPE = "vxlan_gpe"
    ARP_ETH_IPV4 = "arp_eth_ipv4"
    ICMP = "icmp"
    ICMP6 = "icmp6"
    MARK = "mark"
    META = "meta"
    TAG = "tag"
    FUZZY = "fuzzy"


class FlowActionType(Enum):
    # "Simple" actions that don't need parameters
    VOID = "void"
    PASSTHRU = "passthru"
    FLAG = "flag"
    DROP = "drop"
    COUNT = "count"
    MAC_SWAP = "mac_swap"
    DEC_TTL = "dec_ttl"

    # Actions that do need parameters
    JUMP = "jump"
    MARK = "mark"
    QUEUE = "queue"
    RSS = "rss"
    PF = "pf"
    VF = "vf"
    PHY_PORT = "phy_port"
    PORT_ID = "port_id"
    METER = "meter"
    SECURITY = "security"
    OF_SET_MPLS_TTL = "of_set_mpls_ttl"
    OF_DEC_MPLS_TTL = "of_dec_mpls_ttl"
    OF_SET_NW_TTL = "of_set_nw_ttl"
    OF_DEC_NW_TTL = "of_dec_nw_ttl"
    OF_COPY_TTL_OUT = "of_copy_ttl_out"
    OF_COPY_TTL_IN = "of_copy_ttl_in"
    OF_POP_VLAN = "of_pop_vlan"
    OF_PUSH_VLAN = "of_push_vlan"
    OF_SET_VLAN_VID = "of_set_vlan_vid"
    OF_SET_VLAN_PCP = "of_set_vlan_pcp"
    OF_POP_MPLS = "of_pop_mpls"
    OF_PUSH_MPLS = "of_push_mpls"
    VXLAN_ENCAP = "vxlan_encap"
    VXLAN_DECAP = "vxlan_decap"
    NVGRE_ENCAP = "nvgre_encap"
    NVGRE_DECAP = "nvgre_decap"
    RAW_ENCAP = "raw_encap"
    RAW_DECAP = "raw_decap"
    SET_IPV4_SRC = "set_ipv4_src"
    SET_IPV4_DST = "set_ipv4_dst"
    SET_IPV6_SRC = "set_ipv6_src"
    SET_IPV6_DST = "set_ipv6_dst"
    SET_TP_SRC = "set_tp_src"
    SET_TP_DST = "set_tp_dst"
    SET_TTL = "set_ttl"
    SET_MAC_SRC = "set_mac_src"
    SET_MAC_DST = "set_mac_dst"
    INC_TCP_SEQ = "inc_tcp_seq"
    DEC_TCP_SEQ = "dec_tcp_seq"
    INC_TCP_ACK = "inc_tcp_ack"
    DEC_TCP_ACK = "dec_tcp_ack"
    SET_TAG = "set_tag"
    SET_META = "set_meta"
    SET_IPV4_DSCP = "set_ipv4_dscp"
    SET_IPV6_DSCP = "set_ipv6_dscp"
    AGE = "age"
